### ISSUE TITLE
[tpm2-pkcs11] [ubuntu18.04] Error "ModuleNotFoundError: No module named '_cffi_backend'" running /tpm2_ptool addtoken

### ISSUE THREAD

**Issue by ksaye** [Azure/iot-identity-service#217]
I am attempting the instructions here: https://azure.github.io/iot-identity-service/pkcs11/tpm2-pkcs11.html

and getting the error "ModuleNotFoundError: No module named '_cffi_backend'" shown below.  this is when attempting to run:
```
sudo rm -f "$TPM2_PKCS11_STORE/tpm2_pkcs11.sqlite3"
(
    cd ~/src/tpm2-pkcs11/tools &&
    sudo -u aziotks ./tpm2_ptool init --primary-auth '1234' --path /opt/tpm2-pkcs11 &&
    sudo -u aziotks ./tpm2_ptool addtoken \
        --path /opt/tpm2-pkcs11 \
        --sopin "$SO_PIN" --userpin "$PIN" \
        --label "$TOKEN" --pid '1'
)
```

OS: Ubuntu 18.04
Processor: x64 (Linux up2 5.4.0-73-generic #82~18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)
Python: 3.8.0

Python Modules:
```
ksaye@up2:~$ pip3 list installed
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Package               Version
--------------------- -------------------
apturl                0.5.2
asn1crypto            0.24.0
Brlapi                0.6.6
certifi               2018.1.18
chardet               3.0.4
click                 6.7
colorama              0.3.7
command-not-found     0.3
cryptography          2.1.4
cupshelpers           1.0
defer                 1.0.6
distro-info           0.18ubuntu0.18.04.1
httplib2              0.9.2
idna                  2.6
keyring               10.6.0
keyrings.alt          3.0
language-selector     0.1
launchpadlib          1.10.6
lazr.restfulclient    0.13.5
lazr.uri              1.0.3
louis                 3.5.0
macaroonbakery        1.1.3
netifaces             0.10.4
oauth                 1.0.1
olefile               0.45.1
pexpect               4.2.1
Pillow                5.1.0
pip                   21.1.1
protobuf              3.0.0
pyasn1                0.4.2
pyasn1-modules        0.2.1
pycairo               1.16.2
pycrypto              2.6.1
pycups                1.9.73
pygobject             3.26.1
pymacaroons           0.13.0
PyNaCl                1.1.2
pyRFC3339             1.0
python-apt            1.6.5+ubuntu0.5
python-dateutil       2.6.1
python-debian         0.1.32
pytz                  2018.3
pyxdg                 0.25
PyYAML                3.12
reportlab             3.4.0
requests              2.18.4
requests-unixsocket   0.1.5
SecretStorage         2.3.1
setuptools            56.2.0
simplejson            3.13.2
six                   1.11.0
ssh-import-id         5.7
system-service        0.3
systemd-python        234
ubuntu-drivers-common 0.0.0
ufw                   0.36
unattended-upgrades   0.1
urllib3               1.22
wadllib               1.3.2
wheel                 0.30.0
xkit                  0.0.0
zope.interface        4.3.2
```

Actual Error:
```
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (2.1.4)
ksaye@up2:~$ (     cd ~/src/tpm2-pkcs11/tools &&     sudo -u aziotks ./tpm2_ptool init --primary-auth '1234' --path /opt/tpm2-pkcs11 &&     sudo -u aziotks ./tpm2_ptool addtoken         --path /opt/tpm2-pkcs11         --sopin "$SO_PIN" --userpin "$PIN"         --label "$TOKEN" --pid '1'; )
action: Created
id: 2

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ksaye/src/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 30, in <module>
    main()
  File "/home/ksaye/src/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 26, in main
    commandlet.init('A tool for manipulating the tpm2-pkcs11 database')
  File "/home/ksaye/src/tpm2-pkcs11/tools/tpm2_pkcs11/command.py", line 102, in init
    commandlet.get()[d['which']](d)
  File "/home/ksaye/src/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_token.py", line 302, in __call__
    AddTokenCommand.do_token_init(db, path, args)
  File "/home/ksaye/src/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_token.py", line 256, in do_token_init
    pss_sig_good = check_pss_signature(tpm2, pobj_handle, pobject['objauth'])
  File "/home/ksaye/src/tpm2-pkcs11/tools/tpm2_pkcs11/utils.py", line 342, in check_pss_signature
    public_key = pub_numbers.public_key(default_backend())
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 16, in <module>
    from cryptography import utils, x509
  File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 18, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'
```

**Comment by arsing** [comment]
Do you have the `python3-cffi-backend` apt package installed? It ought to have been pulled in as a dep of `python3-cryptography` that you installed at the start of the script.

**Comment by ksaye** [comment]
@arsing, I will check.  FYI, it works fine on Ubuntu 20.04 (so far)

**Comment by ksaye** [comment]
Yes, version 1.11.5-1 is installed with Ubuntu 18.04, as shown below:

```
make[1]: Leaving directory '/home/ksaye/src/tpm2-pkcs11'
action: Created
id: 1

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ksaye/src/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 30, in <module>
    main()
  File "/home/ksaye/src/tpm2-pkcs11/tools/tpm2_pkcs11/tpm2_ptool.py", line 26, in main
    commandlet.init('A tool for manipulating the tpm2-pkcs11 database')
  File "/home/ksaye/src/tpm2-pkcs11/tools/tpm2_pkcs11/command.py", line 102, in init
    commandlet.get()[d['which']](d)
  File "/home/ksaye/src/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_token.py", line 302, in __call__
    AddTokenCommand.do_token_init(db, path, args)
  File "/home/ksaye/src/tpm2-pkcs11/tools/tpm2_pkcs11/commandlets_token.py", line 256, in do_token_init
    pss_sig_good = check_pss_signature(tpm2, pobj_handle, pobject['objauth'])
  File "/home/ksaye/src/tpm2-pkcs11/tools/tpm2_pkcs11/utils.py", line 342, in check_pss_signature
    public_key = pub_numbers.public_key(default_backend())
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 16, in <module>
    from cryptography import utils, x509
  File "/usr/lib/python3/dist-packages/cryptography/x509/__init__.py", line 8, in <module>
    from cryptography.x509.base import (
  File "/usr/lib/python3/dist-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/usr/lib/python3/dist-packages/cryptography/x509/extensions.py", line 18, in <module>
    from cryptography.hazmat.primitives import constant_time, serialization
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/constant_time.py", line 9, in <module>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named '_cffi_backend'
ksaye@tpmtest:~$ sudo apt list --installed | grep python3-cffi-backend

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

python3-cffi-backend/bionic,now 1.11.5-1 amd64 [installed,automatic]
```

I do see a different version with Ubuntu 20.04:

```
ksaye@tpmub2004:~$ sudo apt list --installed | grep python3-cffi-backend
[sudo] password for ksaye:

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

python3-cffi-backend/focal,now 1.14.0-1build1 amd64 [installed,automatic]
ksaye@tpmub2004:~$ cat /etc/issue
Ubuntu 20.04.2 LTS \n \l
```

**Comment by arsing** [comment]
Oh right, `python3-` apt packages don't matter for Ubuntu 18.04 because they'll all be for its default python3 ie Python 3.6. For 3.7 it'll have its own `python3.7-*` packages.

But `apt search python3.7` doesn't show any apt packages, so you'll probably need to install them with pip.

And since there's also no apt package for `python3.7-pip`, you have to do this roundabout method of installing it via `python3-pip` first: https://stackoverflow.com/a/56140616/545475

**Comment by ksaye** [comment]
Thanks @arsing .  Based on your response, I was able to track down the cause.

On Ubuntu 18.04, I install python3.8 and then change the link of /usr/bin/python3 to point to 3.8.  I do this because I was never able to get the ```PYTHON_INTERPRETER=python3.7``` to work, I believe because of the sudo -u command.

Because the command is running as aziotks based on the command ```sudo -u aziotks ./tpm2_ptool```.  That user does not have the cffi module, which seems to be the issue.  to resolve it, after installing python3.8 I now run ```sudo apt install -y python3-pip && sudo pip3 install cryptography cffi```, which solves the issue.

**Comment by arsing** [comment]
>On Ubuntu 18.04, I install python3.8 and then change the link of /usr/bin/python3 to point to 3.8. I do this because I was never able to get the `PYTHON_INTERPRETER=python3.7` to work, I believe because of the sudo -u command.

`sudo` does not inherit env vars by default, yes. You need to forward the env var down, like with `sudo -u aziotks "PYTHON_INTERPRETER=$PYTHON_INTERPRETER" ./tpm2_ptool ...`. Or install the modules system-wide, as you did.
